### ISSUE TITLE
Attempting to compile results in "comparison between signed and unsigned integer expressions" error

### ISSUE THREAD

**Issue by mobilediesel** [mptre/yank#1]
Running make gives this output:

> cc -Os -pedantic -std=c99 -Wall -Werror -Wextra yank.c -o yank  -DVERSION=\"0.4.0\" -DYANKCMD=\"xsel\"
> yank.c: In function ‘tsetup’:
> yank.c:334:8: error: comparison between signed and unsigned integer expressions [-Werror=sign- compare]
> yank.c:334:8: error: signed and unsigned type in conditional expression [-Werror=sign-compare]
> cc1: all warnings being treated as errors
> make: **\* [yank] Error 1

**Comment by mptre** [comment]
Could you supply the output of the following command: `cc --version`

**Comment by mobilediesel** [comment]
> cc (Debian 4.7.2-5) 4.7.2
> Copyright (C) 2012 Free Software Foundation, Inc.
> This is free software; see the source for copying conditions.  There is NO
> warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by mptre** [comment]
Could you try out commit dc717c3?

**Comment by mobilediesel** [comment]
That seems to have done the trick! I'm not even sure what I'm going to use this for yet but since I do most data processing on the command line I'm sure I'll figure it out eventually.

**Comment by mptre** [comment]
Great! Thanks for finding the error. If you find a suitable or creative use-case
please feel free to add to the examples in the README and man page.
