### ISSUE TITLE
Support for out-of-source builds

### ISSUE THREAD

**Issue by elfring** [mptre/yank#12]
How do you think about to benefit from [parallel build trees](https://www.gnu.org/software/automake/manual/html_node/VPATH-Builds.html) also for this software?
Would you like to [support out-of-source](http://cmake.org/Wiki/CMake_FAQ#What_is_an_.22out-of-source.22_build.3F) ([VPATH](https://www.gnu.org/software/make/manual/html_node/General-Search.html)) builds?

**Comment by mptre** [comment]
As stated earlier: I'm not sure on how to handle this kind of issues. PRs to
improve code quality are much welcome.
