### ISSUE TITLE
Fails to build on 32-bit architectures

### ISSUE THREAD

**Issue by sdelafond** [mptre/yank#14]
Here is a bug report I received after packaging yank for Debian:

  | Builds of yank for 32-bit architectures such as i386 have been failing:
  |
  |   yank.c:24:22: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
  |    #define MIN(x, y) (x < y ? x : y)
  |                         ^
  |   yank.c:334:8: note: in expansion of macro 'MIN'
  |       d = MIN((in.v + in.nmemb) - s1,
  |           ^
  |   yank.c:24:30: error: signed and unsigned type in conditional expression [-Werror=sign-compare]
  |    #define MIN(x, y) (x < y ? x : y)
  |                                 ^
  |   yank.c:334:8: note: in expansion of macro 'MIN'
  |       d = MIN((in.v + in.nmemb) - s1,
  |           ^
  |   cc1: all warnings being treated as errors
  |   Makefile:11: recipe for target 'yank' failed
  |
  | I'm not sure why this isn't happening for 64-bit architectures; it
  | might relate to type promotion rules.

Is this something you'd be willling to fix ?

Cheers,

--Seb

**Comment by mptre** [comment]
This issue should be fixed by dc717c3. I just tagged and released v0.4.1. Please
try it out and report back any issues.

**Comment by sdelafond** [comment]
It's all good in v0.4.1:

https://buildd.debian.org/status/package.php?p=yank

Thanks a lot !

**Comment by mptre** [comment]
Great! Please consider submitting a PR with Debian specific install instructions to the README.
