### ISSUE TITLE
Segmentation fault on OS X

### ISSUE THREAD

**Issue by ddelnano** [mptre/yank#21]
I installed yank from the source by issuing `YANKCMD=pbcopy make install`.  I then tried to use yank by doing the command `docker ps | yank` and I got a list of the output.  I then tried to use the arrow keys and received a segmentation fault.  

I am wondering if I may have installed this incorrectly?  Any help would be greatly appreciated!

**Comment by mptre** [comment]
Do you have GDB running on your OS X computer? If you do: could you locate the
segmentation fault. If not (GDB is kind of a hassle to get running on OS X
nowadays) could you send me the output of `docker ps` and step necessary in
order to re-procure the bug.

Could you also attach the output of the following two commands executed from
your local yank directory:

```
gcc --version
make -B
```

Thanks!

**Comment by ddelnano** [comment]
Actually it is working....

When I originally tried it my docker daemon wasn't running so my terminal output was the following

``` bash
Get http:///var/run/docker.sock/v1.20/containers/json: dial unix /var/run/docker.sock: no such file or directory.
* Are you trying to connect to a TLS-enabled daemon without TLS?
* Is your docker daemon up and running?
```

and when I tried to use the arrow keys I got the segmentation fault.

However, if I try something that has a table like structure it works.  For example when my docker daemon is running `docker ps` outputs the following.

``` bash
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
```

Is there a reason for this???  Does yank expect a certain structure to be output?

**Comment by ddelnano** [comment]
As I see [here](https://github.com/mptre/yank/blob/master/yank.c#L230) does it need to be a end of line or tab?  Not sure what the rune function does but I see that the section I referenced doesn't work for spaces.

**Comment by mptre** [comment]
That's definitely a bug. Thanks for taking the time to report it. The upcoming regex[1] release solves this issue when the input is empty.

And no yank doesn't require the input to be formatted in any way.

[1] https://github.com/mptre/yank/pull/20

**Comment by ddelnano** [comment]
👍🏻
