### ISSUE TITLE
Saving and restoring cursor position does not work on OS X Terminal

### ISSUE THREAD

**Issue by elyscape** [mptre/yank#22]
On Terminal.app in OS X (and potentially elsewhere), the escape sequences to save and restore cursor position differ from [those used](https://github.com/mptre/yank/blob/master/yank.c#L29-L30). Specifically, `T_RESTORE_CURSOR` is `"\0338"` and `T_SAVE_CURSOR` is `"\0337"`. This is potentially different on other terminals, too.

**Comment by mptre** [comment]
Thanks for the report and work-around. Instead of using constant capabilities they should be read from the terminfo database. Will definitely look into this.

**Comment by elyscape** [comment]
Agreed. I was just reluctant to submit a pull request that added additional library dependencies.

**Comment by mptre** [comment]
Agreed. Reading the terminfo database without using and linking against the curses library does not seem possible. Is there any other way to query the database? Ideas would be much appreciated.

**Comment by elyscape** [comment]
I mean, one workable but incredibly janky solution would be to just call `tput` at startup for each special character you wanted to use and store the output. I'm looking into better solutions now.

**Comment by mptre** [comment]
But that still requires one to include curses and call `setupterm` etc.?

**Comment by elyscape** [comment]
`tput` is a separate binary. It is provided by the various curses packages, though, now that you mention it, so that option would require curses to be installed, at the very least. To avoid needing to link to curses, you could try calling out to that and fall back on a hardcoded string if it can't be found? Again, janky but workable. Still researching a better solution.

**Comment by elyscape** [comment]
Looking at the source for `tput`, [it appears to call `setupterm`](http://ncurses.scripts.mit.edu/?p=ncurses.git;a=blob;f=progs/tput.c;h=f25cbafbc61f6b2d8dadd4c3d40b83e9decc0076;hb=HEAD#l370).

**Comment by elyscape** [comment]
If you're willing to use curses, it looks like all that you would need to do would be to add something like the following:

``` c
#include <curses.h>
#include <term.h>

static void gettcodes(void);

void
gettcodes(void)
{
    int errno; // won't be used but is necessary to prevent setupterm from quitting on failure
    char *temp;

    // use hardcoded defaults in case of curses failure
    // these variables are globals
    t_save_cursor = T_SAVE_CURSOR;
    t_restore_cursor = T_RESTORE_CURSOR;
    /* more of the same for the other values */

    // setupterm will use the environment variable TERM if you don't provide a term name
    if (setupterm((char *)NULL, 1, &errno) == OK)
    {
        temp = tigetstr("sc");
        if (temp != (char *)NULL && temp != (char *)(-1))
        {
            t_save_cursor = temp;
        }
        temp = tigetstr("rc");
        if (temp != (char *)NULL && temp != (char *)(-1))
        {
            t_restore_cursor = temp;
        }
        /* more of the same for the other values */
    }
}
```

Unfortunately, this would require curses to be installed on the system in order to even run. A way around that would be to allow a compile-time constant to be set to disable curses functionality.

**Comment by elyscape** [comment]
Incidentally, requiring curses to be on the system should be a huge deal, as I believe pretty much every POSIX and POSIX-like system ships with some version of curses.

**Comment by mptre** [comment]
Is a negation missing from the first sentence? Using curses might be the right choice after all. If so I'm more inclined to use it exclusively without the current constants as a fallback. The change would only require a rewrite of the `tputs` function (not tested):

``` c
void
tputs(const char *cap)
{
  const char *s;
  size_t n;

  s = tigetstr(cap);
  n = strlen(s);
  twrite(s, n);
}
```

**Comment by elyscape** [comment]
> Is a negation missing from the first sentence?

Whoops! That is correct.

**Comment by elyscape** [comment]
> The change would only require a rewrite of the `tputs` function (not tested):

The only potential issue with this is that `tputs` is currently also used [on this line](https://github.com/mptre/yank/blob/v0.5.0/yank.c#L390) to write a newline. That could be changed to use `twrite`, though.

**Comment by mptre** [comment]
Good catch. It could probably be replaced with `tputs(T_KEY_DOWN)` as well. Any luck on finding other solutions to query terminfo?

**Comment by elyscape** [comment]
curses appears to be the best solution, unfortunately. It's ubiquitous that it shouldn't really be a problem, though. Should I make a pull request to use it?

**Comment by mptre** [comment]
Patches are always appreciated. Here's my thoughts on the implementation:
- Call setupterm in tsetup
- Make tputs call tigetstr with the supplied capability before writing
- The T_\* macros replacement text should be replaced with the capability name:
  
  #define T_SAVE_CURSOR "sc"
  
  This will simplify the migration and require less changes. However the
  curses library might provide more readable constant for each capability that
  could be used instead. Could be worth investigating.

Other questions/concerns:
- Is it possible to compile a static binary using musl[1] when using the
  curses library?

[1] http://www.musl-libc.org/

**Comment by elyscape** [comment]
So here's something fun. The value for `cursor_left` in the terminfo database for xterm is `^H`. As in backspace. Whereas `cursor_right` is `\E[C`, `cursor_left` is just `^H`. So now I'm trying to figure out how to deal with this situation.

**Comment by elyscape** [comment]
A way around this would be to migrate to using ncurses for all terminal IO, but unfortunately ncurses requires you to use the alternate screen.

**Comment by elyscape** [comment]
Wait a second, I think I just found a way around that by using [`filter`](http://invisible-island.net/ncurses/man/curs_util.3x.html#h3-filter_nofilter). I'll experiment with that some.

**Comment by elyscape** [comment]
Apparently that doesn't work on OS X. That's fantastic.

**Comment by mptre** [comment]
Thanks for the investigation. I'm not to keen on migrating to ncurses. I've been
thinking of writing a separate library which exposes an API to query the
terminfo database. This is far from a trivial fix to this problem but I also
need it for another project and of course it will most definitely be fun.

As for now your Homebrew patch is sufficient? Of course my goal is to solve this
problem in a more sophisticated manner in the future.

**Comment by elyscape** [comment]
> I've been thinking of writing a separate library which exposes an API to query the terminfo database.

Just to be clear, the problem isn't querying the terminfo database. That's easy, even without migrating to using curses entirely. The problem is that the terminfo databases for `xterm` (and variants) and `Apple_Terminal` (which actually appears to never get used) don't have entries with `\E[D` that we can tap to detect the left arrow key, instead using `^H` for `cursor_left`. The databases for `rxvt` and `linux` and a few others have `\E[D` for `cursor_left`, but if we can't rely on the real database then there's not much of a point.

The terminfo database entries aren't really intended for use for filtering input, though. For that, the recommended manner is to use curses for input after setting `keypad(stdscr, TRUE)`, which makes `getch()` return a single int even for fancy things like the left arrow (`260`) or Ctrl+Left (`541`) or whatever. This also avoids issues with varying length terminal codes; for example, Shift+Left is generally pushed as `\E[1;2D`, which is 6 characters long, rather than the 3 that yank currently allocates for its read buffer. As such, ultimately, it might be worth switching to ncurses, even if that would necessitate the use of the alternate screen.

> As for now your Homebrew patch is sufficient?

Yes. Note that `\E7` and `\E8` are older codes and appear to be more widely supported than `\E[s` and `\E[u`, so it might be worth switching to them entirely in the meantime.

**Comment by elyscape** [comment]
SCRATCH ALL THAT I JUST FIGURED OUT HOW TO USE NCURSES FOR INPUT WITHOUT USING THE ALTERNATE SCREEN

**Comment by elyscape** [comment]
Basically, what happens is that when `initscr` or `newterm` is called, it prints the `enter_ca_mode` escape sequence. If we then just print out the `exit_ca_mode` escape sequence, we're back in business.

**Comment by elyscape** [comment]
I can make a pull request that moves all IO over to curses and also drops out of ca_mode by default. As a result, the application will be have identically to how it is now, only with better input handling. Sound good?

**Comment by mptre** [comment]
Thanks for taking the time to investigate this further.

Is the cursor_left capability really a concern? As of writing this yank only
uses and detects key_left. The later capability is consistent and correct in the
terminfo databases I use on a daily basis (linux, screen-256color, st-256color).

Even tho migrating to ncurses would be a feasible and in many ways right
solution I'm not in favor of this change. The enter\exit ca mode solution feels
more like a hack IMHO.

Regarding the (save|restore)_cursor capabilities you're right `\E7' and`\E8'
should be used and would actually solve this issue. Feel free to submit a PR
including the necessary changes to `T_RESTORE_CURSOR' and`T_SAVE_CURSOR'. Your
work should definitely be acknowledged in the Git history.

**Comment by elyscape** [comment]
> Is the cursor_left capability really a concern? As of writing this yank only uses and detects key_left. The later capability is consistent and correct in the terminfo databases I use on a daily basis (linux, screen-256color, st-256color).

The problem is that we're using (for example) `key_right` to detect left keystrokes. Unfortunately, the terminfo library for `xterm` reports `key_right` as `\E0C`, but (in Terminal.app and, likely, other terminal emulators) the left keystroke is `\E[C`, which happens to be stored in `cursor_right`. Same with up (`key_up`: `\E0A`, `cursor_up`: `\E[A`). The problem is left and down: `key_left` and `key_down` are `\E0D` and `\E0B`, respectively, but `cursor_left` is `^H` and `cursor_down` is `\n`. That would be fine except that the left arrow key is actually reported as `\E[D` and the down arrow key is actually reported as `\E[B`, neither of which show up anywhere in the `xterm` terminfo database. Thus the problem.

> Even tho migrating to ncurses would be a feasible and in many ways right solution I'm not in favor of this change. The enter\exit ca mode solution feels more like a hack IMHO.

That's certainly fair, and it's definitely an ugly ugly hack. It does work, but it's inelegant in the extreme.

> Feel free to submit a PR including the necessary changes to `T_RESTORE_CURSOR' and`T_SAVE_CURSOR'.

Will do today.

**Comment by mptre** [comment]
Your patch has been applied. Consider this resolved by now? Thanks for all your contributions.
