### ISSUE TITLE
Add h,j,k,l bindings

### ISSUE THREAD

**Issue by netei** [mptre/yank#27]
To move around in the text, it would be great if we could use the vimlike keybindings 
- h for left
- j for down
- k for up 
- l for right

**Comment by AnimiVulpis** [comment]
I would like to see this feature too

**Comment by mptre** [comment]
Added, see[1].

[1] https://github.com/mptre/yank/commit/adfd575f8e02baa443852c6ccfea9541bf495e89

On Tue, Feb 23, 2016 at 03:31:13AM -0800, netei wrote:

> To move around in the text, it would be great if we could use the vimlike keybindings 
> - h for left
> - j for down
> - k for up 
> - l for right
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/mptre/yank/issues/27

## 

:wq

**Comment by netei** [comment]
Awesome, thanks !

**Comment by AnimiVulpis** [comment]
:+1: thanks
