### ISSUE TITLE
vi-like keybindings

### ISSUE THREAD

**Issue by teoljungberg** [mptre/yank#29]
What do you think about implementing support for `hjkl` to navigate the cursor?

I'll gladly open a PR for it, but first and foremost - I wanted to get your take on it.

**Comment by mptre** [comment]
Already implemented as of release v0.6.4.

On Tue, Mar 15, 2016 at 05:47:04AM -0700, Teo Ljungberg wrote:

> What do you think about implementing support for `hjkl` to navigate the cursor?
> 
> I'll gladly open a PR for it, but first and foremost - I wanted to get your take on it.
> 
> ---
> 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/mptre/yank/issues/29

## 

:wq

**Comment by teoljungberg** [comment]
Great!

Worth noting, 0.6.4 is not released via homebrew yet.

**Comment by mptre** [comment]
Maybe @dongcarl could help out with that since he did the initial brewification.

**Comment by dongcarl** [comment]
@mptre on it

**Comment by dongcarl** [comment]
@mptre https://github.com/Homebrew/homebrew/pull/50152

**Comment by mptre** [comment]
Ty!
