### ISSUE TITLE
Multi-select support

### ISSUE THREAD

**Issue by GSI** [mptre/yank#3]
Fantastic!

Any interest in adding multi-select support to **yank**?

There was a recent post in the Arch forums that explaines the idea pretty well: https://bbs.archlinux.org/viewtopic.php?pid=1565588

If you happen to use **mutt**, you might know it as "toggle" (default hotkey `t`).

**Comment by balta2ar** [comment]
How about [fzf](https://github.com/junegunn/fzf)? Then you can do it like this:

``` bash
ls -lah | fzf -m | xsel
```

**Comment by mptre** [comment]
Interesting idea! I'm a mutt user and aware of the toggle feature. A feature
like this is however not on my roadmap for now. Defining intuitive mappings for
this behavior seems non-trivial at first glance.

**Comment by GSI** [comment]
Thank you both for your comments/ideas. I understand that this might be a little out of **yank**'s scope.
