### ISSUE TITLE
Fedora RPM's

### ISSUE THREAD

**Issue by nmilosev** [mptre/yank#33]
Hey Anton!

Thank you for this very useful tool!

Sorry for opening an issue, just wanted to let you know that I'm packaging your tool for Fedora. The packages are already available in my COPR (Fedora's user repository host) here:

https://copr.fedorainfracloud.org/coprs/nmilosev/yank/

The instructions are as follows:

```
# Fedora 24, 25, 26

sudo dnf copr enable nmilosev/yank
sudo dnf install yank -y
```

`yank-cli` is then available. Sadly we also have the same problem as Ubuntu, where `yank` has been yanked (hehe) from us, so we have to use a name override.

I am also in the process of putting your tool in the official repositories, which you can track here: https://bugzilla.redhat.com/show_bug.cgi?id=1422714

Thank you again for your awesome tool!

Cheers,

Nemanja

PS. I can send you a PR for the `README.md` update with Fedora instructions (COPR for now). Let me know!

**Comment by mptre** [comment]
Thanks for making yank available on Fedora! Please do update the README
with instructions and let me know if you want to receive emails whenever
a new release is available.

**Comment by nmilosev** [comment]
Just sent you a PR with Fedora instructions. :)

I've set the repository on watch, but please notify me when new versions are out, just not to miss them. The address is `nmilosev@fedoraproject.org`. Thanks again!

**Comment by mptre** [comment]
Thanks!
