### ISSUE TITLE
Stripping debug info

### ISSUE THREAD

**Issue by nmilosev** [mptre/yank#35]
Hello, while packaging for Fedora, I noticed you are stripping debug info in the Makefile.

Could you provide insight why is that so, and maybe consider leaving the debug information there?

Kind regards,
Nemanja

**Comment by mptre** [comment]
I tend to follow the common practices from OpenBSD which is the OS I'm
using. On OpenBSD, third-party software is stripped on installation.

You could, however, opt-out by overwriting the `INSTALL_PROGRAM`
variable and remove the `-s` option:

```sh
make INSTALL_PROGRAM="install -m 0755" install
```

**Comment by nmilosev** [comment]
Thanks for the clarification. :)

I wrote a small patch which does the same (it was easier for me): https://pagure.io/yank-rpm/raw/makebuild/f/yank-debuginfo.patch

This patch is used when RPM's are built, because in Fedora packages have debuginfo.

Closing this! Thanks again. :)

**Comment by mptre** [comment]
Great! Let me know if anything else can be improved to make packaging
yank more convenient.

**Comment by nmilosev** [comment]
Maybe add a BINARY_NAME variable in the Makefile, so we can override in case we need to work around packages with `/usr/bin/yank`.

Relevant patch for Fedora: https://pagure.io/yank-rpm/raw/makebuild/f/yank-name-change.patch

I can try and send you a PR if you want. :)

**Comment by mptre** [comment]
> I can try and send you a PR if you want. :)

Please do. Call the variable `PROG` and limit its usage to the name of
binary and not the man-page.
