### ISSUE TITLE
support no-interaction mode

### ISSUE THREAD

**Issue by judovana** [mptre/yank#38]
Hi!

Coll utility this one.  Is it much against the original idea to implement fully user-non-interactive switches?

-A/--all will simply copy all the stdout to clipbard
-A/--all X will copy X-th match to clipboard

so echo a b | yank -A
 - clipboard contains "a b"

so echo a b | yank -A 2
 - clipboard contains "b"

**Comment by mptre** [comment]
Hi,
This is not the intended use-case for yank. However, here's a few ideas.

> so echo a b | yank -A

You could just use the underlying command yank make use of to copy
directly to the clipboard:

```sh
$ echo a b | xsel
```

Make sure to replace `xsel` with the correct command based on your
platform.

> so echo a b | yank -A 2

In this scenario, I assume you would like to use yank's ability to
extract fields. However, I would suggest using `cut(1)` or `awk(1)` if
you already know the which field to copy and the fields are delimited in
a fairly simple manner:

```sh
$ echo a b | awk '{print $2}' | xsel
$ echo a b | cut -d ' ' -f 2 | xsel
```

In more complex situations, for instance: copying the last column on
the second line:

```sh
$ printf '1 2 3\n4 5 6\n7 8 9\n' | awk 'NR==2 {print $NF}' | xsel
```

If the fields are delimited comma and not whitespace:

```sh
$ echo '1,2,3' | awk -F, '{print $1}' | xsel
```

I hope you find the examples useful.

**Comment by judovana** [comment]
Hi!

Indeed the examples are useful!

My "issue" is probably pure laziness  One uses yank and suddenly he found himself repeating the same keystroke sequence.  So yes, where xsel + cut/awk is clear choice, yank  can serve as proper replacement.

Still, feel free to close the issue as the examples are kick-the-lazy  who only wont to pres "up arrow" in terminal ;)

thanx!

**Comment by judovana** [comment]
closed :(

**Comment by mptre** [comment]
My bad, I thought this issue was somewhat resolved?

**Comment by judovana** [comment]
Of course it was! Still the hope was there :( If I will find time to get back to C, You will get and push request;)
