### ISSUE TITLE
Suggestion: Two-dimensional field navigation

### ISSUE THREAD

**Issue by alphapapa** [mptre/yank#4]
This looks really nice!  However, when I watch the GIF, it looks like navigating to the middle of the `ps` output could be laborious.  It would be nice to be able to use the arrow keys and go up/down as well as left/right.

It would be handy to have Emacs-style Ctrl+R/S and/or Vim-style `?`/`/`searching, too.  :)

**Comment by eigengrau** [comment]
I’d second that. Relatedly, navigation should really be bound to the arrow keys in addition to C-P/N/R/S.

Thanks for making yank!

**Comment by mptre** [comment]
Navigating over many fields can for sure be tedious. The `ps` example is
therefore more of a command show-off. If the input contains many potential
fields in between the desired field to select I usually filter the input using
`grep/head/tail` in beforehand.

Internally there's no concept of lines. The input is just treated as a sequence
of bytes which makes navigating to the next/previous line harder to implement.
It can be done but the solution would be more of a hack without changing the
internal representation of the input. This is however something I will consider
changing in the future.

As for a searching I'd recommend filtering the input on beforehand. I want to
keep the #LOC at a minimum and a search feature is therefor out of scope for
this command.

Adding support for the left/right arrow keys makes sense though!

**Comment by mptre** [comment]
I've been giving this issue some more thought recently. Adding support for only
left/right arrows doesn't make sense. I therefor decided to add support for all
arrows allowing navigation in 4 directions. My initial prototype of the changed
input data representation turned out real nice. Stay tuned!

**Comment by alphapapa** [comment]
Sounds great!

**Comment by ff6347** [comment]
+1 on the arrow keys. Also cycling through the fields via TAB would be cool

**Comment by Miserlou** [comment]
Very excited for this development, it's necessary IMO. Yay!

**Comment by lepht** [comment]
+1, with vim cursor keys (hjkl)!

**Comment by mptre** [comment]
See the new arrow-keys branch[1].

[1] https://github.com/mptre/yank/pull/19

**Comment by jiahut** [comment]
cycling through the fields via TAB would be cool!
