### ISSUE TITLE
How to use yank over ssh?

### ISSUE THREAD

**Issue by Fangyh09** [mptre/yank#42]
Hi, I want to use yank over ssh. 
However, I got
```bash
xsel: Can't open display: (null)
```

**Comment by mptre** [comment]
Have you enabled X11 forwarding? `ssh -X user@host`

**Comment by Fangyh09** [comment]
Yes, I tried X11 forwarding just now. 
However,  it could not paste the word I selected when I enter "ctrl v".
I use zsh, iterm2(tried choose `Applications in terminal may access clipboard` in iterm pref).
```bash
ForwardAgent yes
ForwardX11 yes
```

**Comment by Fangyh09** [comment]
It works for bash : )
But why could not it work under zsh?

**Comment by Fangyh09** [comment]
I could use `xclip -o` locally to show the selected words. But, it still failed to use `ctrl v`.

**Comment by Fangyh09** [comment]
I solved finally it by `ps aux | yank | xclip -selection clipboard`: ) Thanks @mptre

**Comment by sarnobat** [comment]
> I solved finally it by `ps aux | yank | xclip -selection clipboard`: ) Thanks @mptre

Could we document this in the README.md?

**Comment by jirutka** [comment]
You can also use [tty-copy](https://github.com/jirutka/tty-copy) to copy to your clipboard directly via the terminal protocol.
