### ISSUE TITLE
Why doesn't `... -- <command>` work?

### ISSUE THREAD

**Issue by lordlycastle** [mptre/yank#56]
So I see the example for kill and other things is to use `xargs` and not the `--` format?

What is the `--` format for running? Is `... yank -- echo` same as `... yank | xargs echo` i.e. `... echo $yank_result`? 

When I do `ps -a | yank -- kill` does not run the `kill` command propertly becase it prints it's usage.

Can you clarify and update the documentation?

**Comment by mptre** [comment]
It depends on the utility used as the yank command.
By default, yank writes the selected field on stdin to the command.
Some commands, like kill, does not accept input on stdin but instead
favors command line arguments. Hence usage of xargs is required.
