### ISSUE TITLE
Setting YANKCMD to "xsel --clipboard"

### ISSUE THREAD

**Issue by bushjames** [mptre/yank#59]
Hi, I want to copy to the desktop clipboard by default i.e by using `xsel --clipboard` I would like to make this the default but setting this via YANKCMD at make time appears impossible. Do you have any suggestions? Many thanks.

**Comment by mptre** [comment]
On Mon, Mar 29, 2021 at 02:05:11AM -0700, James Bush wrote:
> Hi, I want to copy to the desktop clipboard by default i.e by using `xsel --clipboard` I would like to make this the default but setting this via YANKCMD at make time appears impossible. Do you have any suggestions? Many thanks.

The compile time constant YANKCMD does not support arguments. You can
add something like this to your shell rc file, i.e. ~/.bashrc. Make sure
to tweak the yank path according to `which yank`:

yank() (
    /usr/local/bin/yank $@ -- xsel --clipboard
)

**Comment by bushjames** [comment]
many thanks.
