### ISSUE TITLE
Copy all output?

### ISSUE THREAD

**Issue by HR** [mptre/yank#60]
Can you pipe yank and copy all the output of a command with this? Like you can with `pbcopy` on macOS (e.g. `ls -la | pbcopy`)

I thought that just piping it without any args would do that like `ls -la | yank`

**Comment by mptre** [comment]
On Mon, Mar 29, 2021 at 06:08:14PM +0000, Habib Rehman wrote:
> Can pipe and copy all the output of a command with this? Like you can with `pbcopy` on macOS (e.g. `ls -la | pbcopy`)
> 
> I thought that just piping it without any args would do that like `ls -la | yank`

Then we not use pbcopy or xsel? I might be missing something but this
looks like a completely different use case compared to what yank is
intended for, i.e. selecting a portion of the output.

**Comment by HR** [comment]
> On Mon, Mar 29, 2021 at 06:08:14PM +0000, Habib Rehman wrote: Can pipe and copy all the output of a command with this? Like you can with `pbcopy` on macOS (e.g. `ls -la | pbcopy`) I thought that just piping it without any args would do that like `ls -la | yank`
> Then we not use pbcopy or xsel? I might be missing something but this looks like a completely different use case compared to what yank is intended for, i.e. selecting a portion of the output.

Yeah I get that but I just thought since the term `yank` is used for copying, it could also copy all of it. Would just be nice to have just one command for copying.

**Comment by mrzool** [comment]
For what it's worth, I think an `-a` flag to copy all output and exit immediately would make a lot of sense in such a tool and was surprised when I didn't find it in the man page. Anyway, kudos for this tool, it works incredibly well.
