### ISSUE TITLE
jump across filenames with specific extension

### ISSUE THREAD

**Issue by samsaara** [mptre/yank#62]
I have a few PDF files with spaces. How do I jump across those for selection?

I have tried something like these but to no avail:
```
> ls -1 | yank -g '*.pdf'
> ls -1 | yank -g '*.pdf' -d '\r'
> ls -1 | yank -g '*.pdf' -d '\n'
```

Any ideas?

**Comment by Bruno-366** [comment]
how about `ls -1 | yank -l` if its the spaces that are giving you trouble? Or: `ls -1 *.pdf | yank -l` if you just want to show the pdfs

**Comment by samsaara** [comment]
Thanks @Bruno-366, that did it! :) However, I just noticed that if I filter for PDFs on anywhere other than the current directory, it spits out the whole path. So, I had to use `/` separator.... (which is redundant for cwd anyways)

```
ls -1 /path/to/dir/*.pdf | yank -d \/
```
