### ISSUE TITLE
Yank not using xsel on Ubuntu 20/22?

### ISSUE THREAD

**Issue by C-Duv** [mptre/yank#63]
Hello,

On Ubuntu the yanked selection does not seems to go into the clipboard.

Steps to reproduce:

```Shell
echo "failure" | xsel -ib
env | yank-cli -d =
# (select any text, say "HOME" and press the enter key)
xsel -ob
```

Expected results:

`xsel -ob` should output "HOME".

Obtained result:

`xsel -ob` outputs "failure".

The following (using `xsel -ib` as the yank command) works (it outputs "HOME")

```Shell
echo "failure" | xsel -ib
env | yank-cli -d = -- xsel -ib
xsel -ob
```

Tested on both Ubuntu 20.04 and Ubuntu 22.04 with yank version 1.2.0-1 and xsel version 1.2.0.

Is there a configuration file or environment variable to tell/force `yank` to use a given yank command?

**Comment by mptre** [comment]
> Is there a configuration file or environment variable to tell/force `yank` to use a given yank command?

You can make use of a shell alias to achieve what you hopefully want:

	https://github.com/mptre/yank/issues/59#issuecomment-809215698

**Comment by C-Duv** [comment]
I see, thanks, I'll try this workaround.

But it is yank supposed to work with xsel out of the box? What have I done wrong?

**Comment by mptre** [comment]
> But it is yank supposed to work with xsel out of the box? What have I done wrong?

xsel defaults to using the primary clipboard, i.e. `xsel -op` should
output the copied text.

**Comment by C-Duv** [comment]
Oh... I now get it.

I was wrong about how `xsel` works and how to use it (I only used the _CLIPBOARD selection_, `-b`), it's now way more clear, thanks.

So everything works fine, I "just" have to press the middle mouse button to paste instead of [Ctrl]+[V] (or [Ctrl]+[Shift]+[V] in a terminal).
