### ISSUE TITLE
`--select-1` option similar to fzf

### ISSUE THREAD

**Issue by MikaelElkiaer** [mptre/yank#64]
In case there is only one field - both with or without a pattern - it would be nice to optionally just have that outputted, without any prompt.

Like how `--select-1`/`-1` behaves in [fzf](https://man.archlinux.org/man/fzf.1.en#Scripting).

I would like to do it. But after having a quick look at the source I realised that I am rusty in C.
Perhaps this is where an extra case is needed if the arg is present? https://github.com/mptre/yank/blob/1a7aad0d1bd3be1652eb03c574ad01de19a321f2/yank.c#L348

**Comment by mptre** [comment]
Thanks for the suggestion, see #65. Does it do the expected thing?

**Comment by MikaelElkiaer** [comment]
> Thanks for the suggestion, see #65. Does it do the expected thing?

Thanks for moving quickly on this. It looks like it does the trick, will build and try it out ASAP.

**Comment by MikaelElkiaer** [comment]
> > Thanks for the suggestion, see #65. Does it do the expected thing?
> 
> Thanks for moving quickly on this. It looks like it does the trick, will build and try it out ASAP.

Works like a charm! Very nice.
Can't believe how I never discovered this until now. This covers some nice cases that `fzf` doesn't, while also mitigating the need of a full-blown TUI.
