### ISSUE TITLE
Addition of a build system generator

### ISSUE THREAD

**Issue by elfring** [mptre/yank#7]
I suggest to reuse a higher level build system than [your current small make file](https://github.com/mptre/yank/blob/9693dd69b5b7bc2f5a82c22093ff4d50ab0ee443/Makefile#L1) so that powerful checks for software features will become easier.
- [CMake](http://cmake.org/)
- [Autotools](http://www.gnu.org/software/autoconf/#TOCintroduction)

**Comment by mptre** [comment]
For a small project like this my opinion is that a small Makefile like the
current one is sufficient. Is there any feature in the compile/install procedure
missing at the moment?

**Comment by elfring** [comment]
- Does [a tool like "autoscan"](https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.69/html_node/autoscan-Invocation.html) show any software dependencies that you find worth for further considerations?
- How do you think about to support more development environments by [the reuse of build system generators](http://www.cmake.org/cmake/help/v3.3/manual/cmake-generators.7.html#cmake-generators)?

**Comment by mptre** [comment]
I'm not sure on how to handle this issue. PRs to improve code quality are much
welcome.
